## 2. Pandas

### 2.1 Series

In [1]:
import numpy as np
import pandas as pd

In [21]:
np.__version__, pd.__version__

('1.24.3', '1.5.3')

- Series 생성
    - numpy 1차원 배열(value) + index

In [3]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=['서울', '부산', '인천', '대구'])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [4]:
type(s)

pandas.core.series.Series

In [5]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [6]:
# index를 별도로 성정하지 않으면, 인덱스는 0, 1, 2, ...이 된다.
pd.Series(np.arange(11, 15)) 

0    11
1    12
2    13
3    14
dtype: int32

In [7]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [8]:
s.name = '인구'
s.index.name = '도시'
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

- 시리즈 연산 - 벡터화 연산이 가능

In [10]:
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

- 인덱싱

In [12]:
s['서울'], s[0], s.서울

(9904312, 9904312, 9904312)

In [13]:
s['대구'], s[3], s.대구, s[-1]

(2466052, 2466052, 2466052, 2466052)

In [14]:
# 배열 인덱싱 - 결과는 시리즈
s[[0, 1, 3]]

도시
서울    9904312
부산    3448737
대구    2466052
Name: 인구, dtype: int64

In [15]:
s[['서울', '인천']]

도시
서울    9904312
인천    2890451
Name: 인구, dtype: int64

In [17]:
# 인덱스로 조건식
s[(s > 2500000) & (s < 5000000)]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [18]:
s[s % 2 ==0]

도시
서울    9904312
대구    2466052
Name: 인구, dtype: int64

- 슬라이싱

In [19]:
# 숫자 인덱스로 하는 슬라이싱은 넘파이와 동일
s[:2]

도시
서울    9904312
부산    3448737
Name: 인구, dtype: int64

In [20]:
# 인덱스 문자열로 슬라이싱을 하는 경우에는 : 뒤 인덱스를 포함
s[:'인천']

도시
서울    9904312
부산    3448737
인천    2890451
Name: 인구, dtype: int64

- 시리즈와 딕셔너리

In [22]:
# 인덱스가 시리즈에 있는지 여부
'서울' in s, '대전' in s

(True, False)

In [23]:
for key, value in s.items():
    print(f'{key}: {value}')

서울: 9904312
부산: 3448737
인천: 2890451
대구: 2466052


In [24]:
d = {"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158}
s2 = pd.Series(d)
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [26]:
# 인덱스의 순서를 정하고 싶으면, 인덱스를 별도로 설정해야 함
s2 = pd.Series(d, index=['서울', '부산', '인천', '대전'])
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

- 인덱스 기반 연산

In [27]:
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [28]:
ds.notna()      # ds.notnull()과 동일

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [29]:
ds[ds.notna()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [31]:
# 증가율(% 단위)
rs = (s - s2) / s2 * 100
rs = rs[rs.notna()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

- 데이터의 갱신, 추가, 삭제

In [32]:
rs['부산'] = 1.64
rs[1] = 2.83
rs.인천 = 9.82
rs

부산    1.64
서울    2.83
인천    9.82
dtype: float64

In [34]:
rs['광주'] = 1.51   # 추가하는 경우 rs[3], rs.광주 는 사용할 수 없음
rs

부산    1.64
서울    2.83
인천    9.82
광주    1.51
dtype: float64

In [37]:
del rs['부산']      # 삭제하는 경우 rs[0], rs.부산 은 사용할 수 없음
rs

서울    2.83
인천    9.82
광주    1.51
dtype: float64

- 연습문제 4.1.1

In [38]:
s1 = pd.Series(np.arange(11, 15), index=['a', 'b', 'c', 'x'])
s2 = pd.Series(np.arange(31, 39, 2), index=['a', 'b', 'c', 'y'])
print(s1)
print(s2)

a    11
b    12
c    13
x    14
dtype: int32
a    31
b    33
c    35
y    37
dtype: int32


In [39]:
print(s1 + s2, s1 - s2, s1 * s2, s1 /s2, sep='/n')

a    42.0
b    45.0
c    48.0
x     NaN
y     NaN
dtype: float64/na   -20.0
b   -21.0
c   -22.0
x     NaN
y     NaN
dtype: float64/na    341.0
b    396.0
c    455.0
x      NaN
y      NaN
dtype: float64/na    0.354839
b    0.363636
c    0.371429
x         NaN
y         NaN
dtype: float64


- 중요한 method

In [41]:
dice = pd.Series(np.random.randint(1, 7, 10))
dice

0    6
1    5
2    6
3    1
4    2
5    5
6    1
7    4
8    2
9    2
dtype: int32

In [42]:
# 요소의 갯수
dice.count(), dice.size

(10, 10)

In [43]:
# 고유한 값
dice.unique()

array([6, 5, 1, 2, 4])

In [47]:
# 고유한 값의 갯수
dice.nunique()

5

In [48]:
# 고유한 값 별로 갯수
dice.value_counts()

2    3
6    2
5    2
1    2
4    1
dtype: int64

In [50]:
np.unique(dice.values, return_counts = True)

(array([1, 2, 4, 5, 6]), array([2, 3, 1, 2, 2], dtype=int64))